import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div class="table-responsive" className={styles.container}>
      <Head>
        <title>DG IMPLANTES - BANCO DE HORAS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <br></br>

      <main className={styles.main}>
      
        <h1>
        <Image src="/dgimplantes.png" alt="Dg Logo" width={180} height={100} />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Controle de Banco de Horas
        </h1>

        <hr></hr>



        <table class="table table-striped text-center">
  <thead>
    <tr>
      <th scope="col" class="text-start">Nomes</th>
      <th scope="col">Banco de Horas</th>
      <th scope="col">Janeiro</th>
      <th scope="col">Fevereiro</th>
      <th scope="col">Marco</th>
      <th scope="col">Abril</th>
      <th scope="col">Maio</th>
      <th scope="col">Junho</th>
      <th scope="col">Total Acumulado</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row" class="text-start">GABRIELY</th>
      <td class="text-danger">-44:02</td>
      <td>00:38</td>
      <td>09:58</td>
      <td class="text-danger">-02:53</td>
      <td class="text-danger">-14:34</td>
      <td>04:29</td>
      <td>00:00</td>
      <td class="text-danger">-46:24</td>    
    </tr>
    <tr>
      <th scope="row" class="text-start">LUCIANA</th>
      <td>19:18</td>
      <td>11:10</td>
      <td>08:25</td>
      <td>02:34</td>
      <td>05:07</td>
      <td>09:21</td>
      <td>00:00</td>
      <td class="text-success">55:55</td> 
    </tr>
    <tr>
      <th scope="row" class="text-start">MONICA</th>
      <td>00:00</td>
      <td class="text-danger">-12:32</td>
      <td>03:33</td>
      <td class="text-danger">-07:54</td>
      <td>03:27</td>
      <td>26:28</td>
      <td>00:00</td>
      <td class="text-success">13:02</td>
    </tr>

    <tr>
      <th scope="row" class="text-start">FABIOLA</th>
      <td class="text-danger">-05:01</td>
      <td>06:10</td>
      <td>00:28</td>
      <td class="text-danger">-02:58</td>
      <td class="text-danger">-05:08</td>
      <td>10:40</td>
      <td>00:00</td>
      <td class="text-success">04:11</td>
    </tr>

    <tr>
      <th scope="row" class="text-start">FERNANDA</th>
      <td class="text-danger">-216:32</td>
      <td class="text-danger">-14:40</td>
      <td class="text-danger">-17:09</td>
      <td class="text-danger">-19:17</td>
      <td class="text-danger">-23:32</td>
      <td class="text-danger">-10:17</td>
      <td>00:00</td>
      <td class="text-danger">-301:27</td>
    </tr>

    <tr>
      <th scope="row" class="text-start">ANA KAROLYNE</th>
      <td class="text-danger">-62:18</td>
      <td>23:09</td>
      <td class="text-danger">-03:53</td>
      <td>09:02</td>
      <td>04:06</td>
      <td>04:44</td>
      <td>00:00</td>
      <td class="text-danger">-25:10</td>
    </tr>

  </tbody>
</table>


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
      </main>

      
    </div>
  )
}
